### ISSUE TITLE
permission_ add WebSite, bitcoin address and donate link on fdroid

### ISSUE THREAD

**Issue by ghost** [Radiokot/ln-addr-to-invoice#2]
@Radiokot 
* is it **ok to add** WebSite, bitcoin address and donate link given in repo & donate link_ https://radiokot.com.ua/tip
* WebSite, bitcoin address and donate link in [app fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/ua.com.radiokot.lnaddr2invoice.yml) will create a link on fdroid client

**Comment by Radiokot** [comment]
Hi. I agree, it is a good idea to add bitcoin address `bc1qx7nja8gaykyd4encua90wnz8rygt572ddgnzmg` and a link to the donation page `https://radiokot.com.ua/tip` to the F-Droid metadata. 
Please, do it if you can.
Thank you.

**Comment by Radiokot** [comment]
Understand.
I confirm that `https://radiokot.com.ua/p/ln-addr-to-invoice` is the project website, you can add it to the metadata.
