### ISSUE TITLE
[ISSUE] Failed to load username info. The link must contain and email like address 

### ISSUE THREAD

**Issue by ghost** [Radiokot/ln-addr-to-invoice#4]
Hi. I installed your app then clicked on the lightning icon "zap" on Nostr. After 2 seconds of clicking the lighting bolt I get this message pop-up at the bottom of the screen.

"Failed to load username info. The link must contain and email like address"

If I go on someone's profile and and click on the lightning address I get this message pop:

"The link must contain and email like address"

I've tried many profiles and same tiny pop-up.

Nostr: v0.89.7 fdroid
Phone OS: LineageOS

![Screenshot_20240731-073840_Gallery](https://github.com/user-attachments/assets/0c12f53a-d5a4-432f-80b2-80bb93203e61)

**Comment by Radiokot** [comment]
Hi. Thank you for zapping my posts 😄 However, you don't need to use this app with Amethyst – it creates invoices itself when you click "Zap" and select the amount. You must select your Lightning wallet instead of "LN Address to Invoice" when the system selection popup appears. If you don't have a Lightning wallet, you need to install one. I recommend Wallet of Satoshi as a good start.

**Comment by git-3000** [comment]
hmm.. I didn't have any wallet installed. All i had was Amethyst & your app installed. When i clicked on "zap" nothing came up other than that "failed" message.

After installing your wallet of satoshi. Now when i click on "zap" i see the "system selection screen and it asks me when app do i want to open it with.

![wos](https://github.com/user-attachments/assets/d3ccb097-771a-4260-8a22-161edbb11bc6)


If i pick wallet of satoshi then it takes me to their app and i can pay/zap the invoice. 
![wos2](https://github.com/user-attachments/assets/3e10ddf9-c4b1-41cb-a204-01e00b61164d)


if i pick your app it gives me "Failed to load username info. The link must contain and email like address"
 
i guess it's not a bug. Your app is working fine.

I thought your app was supposed going to let me copy the lnbc address after clicking on "Zap" so i can take that address and pay the invoice. 
Wallet of satoshi won't let me copy the address on their app.

Who generates the lnbc address your address? your app or the wallet of satoshi?
can you make your app pop-up instead and let me copy the lnbc address
i want to take that address and pay the invoice with btcpay server and not wallet of satoshi

**Comment by Radiokot** [comment]
Got you.
The lnbc**** invoice gets created in Amethyst, so the email-like address is not getting into Wallet of Satoshi or my app.
It seems not possible to copy the address in Amethyst. 
For your use case, I recommend Zeus wallet. You can either connect to your Lightning node, or copy the invoice from it:
![Screenshot_20240731_210623_ZEUS](https://github.com/user-attachments/assets/50b3f570-e807-4de7-ae87-cf88eca51630)
![Screenshot_20240731_210627_ZEUS](https://github.com/user-attachments/assets/d5a741aa-1a3a-49a6-a97e-fb4dd178b825)

**Comment by git-3000** [comment]
it worked!! i downloaded zeus and it opens up when i click on the zap button. I click on the top right qr code to see the lightning invoice address. I remove the "lightning:" part and then go to RTL inside btcpay server and paste it in the "Send payment" and it allows me to send the zap 

Thank you!!

**Comment by Radiokot** [comment]
Awesome 🎉
